const char ERROR_PAGE[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>Victor probando cosas</title>"
"</head>"
"<body>"
"<h1>tas ekibocao de url tronco k aces x favor no hagas las cosas mal xd</h1>"
"</body>"
"</html>";

const char TEST_PAGE[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>Main page</title>"
"</head>"
"<body>"
"<h1>Welcome to my house</h1>"
"Turn <a href=\"/on\">ON</a><br>"
"Turn <a href=\"/off\">OFF</a><br>"
"<p><span id=\"datetime\"></span></p>"
"<script>"
"var dt = new Date();"
"document.getElementById(\"datetime\").innerHTML = dt.toLocaleTimeString();"
"</script>"
"</body>"
"</html>";

const char MAIN_PAGE[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<title>Main page</title>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n"
"<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Lato\">\n"
"<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n"
"<style>\n"
"body {font-family: \"Lato\", sans-serif}\n"
".mySlides {display: none}\n"
"</style>\n"
"<body>\n"
"<div class=\"w3-top\">\n"
"<div class=\"w3-bar w3-black w3-card\">\n"
"<a class=\"w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right\" href=\"javascript:void(0)\" onclick=\"myFunction()\" title=\"Toggle Navigation Menu\"><i class=\"fa fa-bars\"></i></a>\n"
"<a href=\"#\" class=\"w3-bar-item w3-button w3-padding-large\">HOME</a>\n"
"<a href=\"#band\" class=\"w3-bar-item w3-button w3-padding-large w3-hide-small\">ALARM</a>\n"
"</div>\n"
"</div>\n"
"<div class=\"w3-content\" style=\"max-width:2000px;margin-top:46px\">\n"
"<div class=\"w3-container w3-content w3-center w3-padding-64\" style=\"max-width:800px\" id=\"band\">\n"
"<h2 class=\"w3-wide\">PROJECT A</h2>\n"
"<p class=\"w3-opacity\"><i>Tu alarma accesible desde donde quieras</i></p>\n"
"<p class=\"w3-justify\">Project A es el proyecto desarrollado para la asignatura de Informática Industrial. Consta de una alarma que enciende la luz de tu habitación para que te despereces más rápido que nunca. Estamos muy orgullosos de ofrecerle nuestro servicio y conseguir que sea más productivo todas y cada una de sus mañanas. Gracias por elegirnos.</p>\n"
"<div class=\"w3-row w3-padding-32\">\n"
"<div class=\"w3-third\">\n"
"<p>Turn <a href=\"/on\">ON</a></p>\n"
"</div>\n"
"<div class=\"w3-third\">\n"
"<p><span id=\"datetime\"></span></p>\n"
"</div>\n"
"<div class=\"w3-third\">\n"
"<p>Turn <a href=\"/off\">OFF</a></p>\n"
"</div>\n"
"</div>\n"
"</div>\n"
"</div>\n"
"<footer class=\"w3-container w3-padding-64 w3-center w3-opacity w3-light-grey w3-xlarge\">\n"
"<p class=\"w3-medium\">Powered by Vistor</p>\n"
"</footer>\n"
"<script>\n"
"function myFunction() {\n"
"var x = document.getElementById(\"navDemo\");\n"
"if (x.className.indexOf(\"w3-show\") == -1) {\n"
"x.className += \" w3-show\";\n"
"} else { \n"
"x.className = x.className.replace(\" w3-show\", \"\");\n"
"}\n"
"}\n"
"var myVar = setInterval(myTimer, 1000);\n"
"function myTimer() {\n"
"var d = new Date();\n"
"var t = d.toLocaleTimeString();\n"
"document.getElementById(\"datetime\").innerHTML = t;\n"
"}\n"
"</script>\n"
"</body>\n"
"</html>";
